enc = '''BAAAABAA BAABABAA
ABAAAABA AAABAABB AAAAAABB
AAABABBA AABAABBA AABBABBA AAABAABB AABAAABB AABBAABB
AABBABBB AABBAABB AABBABBA AABAABBB AABBAABB ABAAABBB
AABBABBB BBBBABBA AABBABBA BAABABBA AAABABBA BBAAABBA BABBABBB BAABABBA BBBBABAB BBAAABBA BBBBABBA ABBAABBB ABABABBA BBBBABAB BABAABBA AAABABBA ABBAABBB AAABABBA BBBBABAB AABBABBB AAABABBA BAABABBA ABAAABBA BBBBABAB BBBAABBA BBBBABBA BBBBABAB BBBBABBA BBBAABBA ABABABBA BBBBABAB ABABABBA ABBAABBB ABABABBA AABAABBB BBABABBB'''.splitlines()

for line in enc:
    for m in line.split():
        m = m[4:] + m[:4]
        m = m.replace('A', '0').replace('B', '1')
        print(chr(int(m, 2)), end='')
    print()